apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserver
  labels:
    app: codeserver
type: Opaque
data:
  PASSWORD: Y2hhbmdlaXQ=
  SUDO_PASSOWRD: Y2hhbmdlaXRzdWRv

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-config
  namespace: codeserver
  labels:
    app: codeserver
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-188.166.207.3.nip.io