---
apiVersion: v1
kind: Namespace
metadata:
  name: bggns
  labels: 
    app: bgg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-deploy
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
        app: bgg
        name: bggdb-po
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggdb-port
          containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc 
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: bggdb-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-deploy
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      name: bggapp-po
  template:
    metadata:
      name: bggapp-po
      labels:
        app: bgg
        name: bggapp-po
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggapp-port
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    name: bggapp-svc
    app: bgg
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggapp-po
  ports:
  - name: bggapp-port
    port: 3000
    targetPort: bggapp-port

