---
apiVersion: v1
kind: Namespace
metadata:
  name: minio

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minio
  labels: 
    app: minio
    name: minio-ing
spec:
  ingressClassName: nginx
  rules:
  - host: data-188.166.207.3.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9000
  - host: console-188.166.207.3.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio
  labels:
    app: minio
    name: minio-hsvc
spec:
  clusterIP: None
  selector:
    name: minio-po
    app: minio
  ports:
  - name: minio-hsvc-data-port
    port: 9000
    targetPort: 9000
  - name: minio-hsvc-web-port
    port: 9001
    targetPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio
  labels:
    app: minio
    name: minio-svc
spec:
  type: ClusterIP
  selector:
    name: minio-po
    app: minio
  ports:
  - name: minio-svc-data-port
    port: 9000
    targetPort: 9000
  - name: minio-svc-web-port
    port: 9001
    targetPort: 9001

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio
  labels:
    app: minio
    name: minio-sts
spec:
  serviceName: minio-hsvc
  replicas: 4
  selector: 
    matchLabels:
      app: minio
      name: minio-po
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      name: minio
      labels:
        app: minio
        name: minio-po
    spec:
      initContainers:
      - name: busybox
        image: busybox 
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh 
        - -c
        - "chown 1001:1001 /data"
        volumeMounts:
        - name: data-vol
          mountPath: /data

      containers:
      - name: minio-container
        image: bitnami/minio
        imagePullPolicy: IfNotPresent
        command:
        - minio
        - server
        - --address=:9000
        - --console-address=:9001
        - http://minio-sts-{0...3}.minio-hsvc.minio.svc.cluster.local/data
        ports:
        - name: api-port
          containerPort: 9000
        - name: data-port
          containerPort: 9000
        envFrom:
        - configMapRef:
            name: minio-config
        - secretRef:
            name: minio-secret
        volumeMounts:
        - name: data-vol
          mountPath: /data
        # livenessProbe:
        #   httpGet: 
        #     path: /minio/health/live
        #     port: 900
        # readinessProbe:
        #   httpGet: 
        #     path: /minio/health/ready
        #     port: 900
        # resources:
        #   requests:
        #     cpu: 200m
        #     memory: 250Mi
        #   limits:
        #     cpu: 200m
        #     memory: 250Mi
